/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FlukierJupiter (https://sketchfab.com/FlukierJupiter)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/scales-2ed4e14bb69944078ef0bb862b256b2a
title: Scales
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

const path = "assets/models/scales/scene.gltf";
const path2 = "assets/models/scales/textures/";
export function BalanceModel(props) {
  const props2 = useTexture({
    map: path2 + "01_-_Default_baseColor.png",

    normalMap: path2 + "01_-_Default_normal.png",
    roughnessMap: path2 + "01_-_Default_metallicRoughness.png",
  });

  const { nodes, materials } = useGLTF(path);
  console.log(materials);
  return (
    <group scale={0.1} position={[0,-1.5,0]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -1.62]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["Scales_LP_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            ></mesh>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(path);
