/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Powerbyte7 (https://sketchfab.com/Powerbyte7)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/calculator-d9ffbc4bbe1044bb902e1dddac52b0de
title: Calculator
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const path = "assets/models/calculator/scene.gltf";
export function CalculatorModel(props) {
  const { nodes, materials } = useGLTF(path);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload(path);
